src/Entity/Person.php
<?php

namespace App\Entity;

use App\Repository\PersonRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PersonRepository::class)
 */
class Person
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $sex;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }
}

src/Form/PersonType.php
<?php

namespace App\Form;

use App\Entity\Person;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class PersonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('surname')
            ->add('last_name')
            ->add('age')
            ->add('sex', ChoiceType::class, [
                'label' => 'Sex',
                'choices' => [
                    'Male' => 'Male',
                    'Female' => 'Female',
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Person::class,
        ]);
    }
}

src/Controller/PersonController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use App\Form\PersonType;
use App\Repository\PersonRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class PersonController extends AbstractController
{
    /**
     * @Route("/", name="person_index", methods={"GET"})
     */
    public function index(PersonRepository $personRepository, Request $request): Response
    {
        $searchTerm = $request->query->get('search');
        $people = $personRepository->findBySearchTerm($searchTerm);

        $totalIndividuals = count($people);
        $totalMales = count(array_filter($people, function ($person) {
            return $person->getSex() === 'Male';
        }));
        $totalFemales = count(array_filter($people, function ($person) {
            return $person->getSex() === 'Female';
        }));

        $percentageMales = ($totalIndividuals > 0) ? round(($totalMales / $totalIndividuals) * 100, 2) : 0;
        $percentageFemales = ($totalIndividuals > 0) ? round(($totalFemales / $totalIndividuals) * 100, 2) : 0;

        return $this->render('person/index.html.twig', [
            'people' => $people,
            'totalIndividuals' => $totalIndividuals,
            'percentageMales' => $percentageMales,
            'percentageFemales' => $percentageFemales,
        ]);
    }

    /**
     * @Route("/new", name="person_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $person = new Person();
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($person);
            $entityManager->flush();

            return $this->redirectToRoute('person_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('person/new.html.twig', [
            'person' => $person,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="person_show", methods={"GET"})
     */
    public function show(Person $person): Response
    {
        return $this->render('person/show.html.twig', [
            'person' => $person,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="person_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Person $person): Response
    {
        $form = $this->createForm(PersonType::class, $person);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('person_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('person/edit.html.twig', [
            'person' => $person,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="person_delete", methods={"POST"})
     */
    public function delete(Request $request, Person $person): Response
    {
        if ($this->isCsrfTokenValid('delete' . $person->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($person);
            $entityManager->flush();
        }

        return $this->redirectToRoute('person_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/person/_delete_form.html.twig
<form method="post" action="{{ path('app_person_delete', {'id': person.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ person.id) }}">
    <button class="btn">Delete</button>
</form>

templates/person/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/person/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div style="max-width: 400px; margin: auto; padding: 20px;">

		<h1>Edit Person</h1>

		{{ form_start(form) }}

		<div style="margin-bottom: 10px;">
			{{ form_label(form.surname) }}
			{{ form_widget(form.surname) }}
		</div>

		<div style="margin-bottom: 10px;">
			{{ form_label(form.last_name) }}
			{{ form_widget(form.last_name) }}
		</div>

		<div style="margin-bottom: 10px;">
			{{ form_label(form.age) }}
			{{ form_widget(form.age) }}
		</div>

		<div style="margin-bottom: 10px;">
			{{ form_label(form.sex) }}
			{{ form_widget(form.sex) }}
		</div>

		<button type="submit" style="padding: 10px; background-color: #007bff; color: #fff; border: none; border-radius: 5px;">Update</button>
		{{ form_end(form) }}

		<a href="{{ path('person_index') }}" style="text-decoration: none; display: block; margin-top: 10px; color: #007bff;">Back to the list</a>

	</div>
{% endblock %}

templates/person/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div style="max-width: 800px; margin: auto; padding: 20px;">

		<h1 style="margin-bottom: 20px;">CRUD Operation</h1>

		<form method="get" action="{{ path('person_index') }}" style="margin-bottom: 20px;">
			<label for="search" style="margin-right: 10px;">Search:</label>
			<input type="text" name="search" id="search" value="{{ app.request.query.get('search') }}">
			<button type="submit" style="margin-left: 10px;">Search</button>
		</form>

		<table style="width: 100%; border-collapse: collapse; margin-bottom: 40px;text-align: left;">
			<thead>
				<tr style="background-color: #f2f2f2;">
					<th style="padding: 10px;">Surname</th>
					<th style="padding: 10px;">Last Name</th>
					<th style="padding: 10px;">Age</th>
					<th style="padding: 10px;">Sex</th>
					<th style="padding: 10px;">Action</th>
				</tr>
			</thead>
			<tbody>
				{% for person in people %}
					<tr style="border-bottom: 1px solid #ddd;">
						<td style="padding: 10px;">{{ person.surname }}</td>
						<td style="padding: 10px;">{{ person.lastName }}</td>
						<td style="padding: 10px;">{{ person.age }}</td>
						<td style="padding: 10px;">{{ person.sex }}</td>
						<td style="padding: 10px;">
							<a href="{{ path('person_edit', {'id': person.id}) }}" style="margin-right: 5px;">Edit</a>
							<a href="{{ path('person_delete', {'id': person.id}) }}" onclick="return confirm('Are you sure?')">Delete</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

		<a href="{{ path('person_new') }}" style="text-decoration: none; padding: 10px; background-color: #28a745; color: #fff; border-radius: 5px;">Add Person</a>

		<div style="margin-top: 20px;">
			<p>Total Individuals:
				{{ totalIndividuals }}</p>
			<p>Percentage of Males:
				{{ percentageMales }}%</p>
			<p>Percentage of Females:
				{{ percentageFemales }}%</p>
		</div>

	</div>
{% endblock %}

templates/person/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div style="max-width: 400px; margin: auto; padding: 20px;">

		<h1>Create a New Person</h1>

		{{ form_start(form) }}

		<div style="margin-bottom: 10px;">
			{{ form_label(form.surname) }}
			{{ form_widget(form.surname) }}
		</div>

		<div style="margin-bottom: 10px;">
			{{ form_label(form.last_name) }}
			{{ form_widget(form.last_name) }}
		</div>

		<div style="margin-bottom: 10px;">
			{{ form_label(form.age) }}
			{{ form_widget(form.age) }}
		</div>

		<div style="margin-bottom: 10px;">
			{{ form_label(form.sex) }}
			{{ form_widget(form.sex) }}
		</div>

		<button type="submit" style="padding: 10px; background-color: #28a745; color: #fff; border: none; border-radius: 5px;">Create</button>
		{{ form_end(form) }}

		<a href="{{ path('person_index') }}" style="text-decoration: none; display: block; margin-top: 10px; color: #28a745;">Back to the list</a>

	</div>
{% endblock %}

templates/person/show.html.twig
{# templates/person/show.html.twig #}

{% extends 'base.html.twig' %}

{% block body %}
	<h1>Person</h1>

	<table border="1">
		<tbody>
			<tr>
				<th>Surname</th>
				<td>{{ person.surname }}</td>
			</tr>
			<tr>
				<th>Last Name</th>
				<td>{{ person.lastName }}</td>
			</tr>
			<tr>
				<th>Age</th>
				<td>{{ person.age }}</td>
			</tr>
			<tr>
				<th>Sex</th>
				<td>{{ person.sex }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('person_index') }}">Back to the list</a>
{% endblock %}